project:
  type: book
  output-dir: docs

book:
  title: "Esquemas de clases Fondecyt"
  author: "Pablo Pérez-Ahumada, Daniela Olivares-Collío"
  date: today
  chapters:
    - index.qmd
    - 01-proce-data-conclat-cl.qmd
    - 02-esquemas-clases-cl.qmd
    - 03-proce-data-conclat-ar.qmd
    - 04-esquemas-clases-ar.qmd
    - 05-proc-marxism-clases-cl.qmd
    # - 06-graph-clases-cl.qmd
    # - 03-proce-data-conclat-ar.qmd
    # - 04-esquemas-clases-ar.qmd
    # - 05-descriptivos-rodolfo.qmd
    # - 06-descriptivos-clases.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: es
  pdf:
    documentclass: scrreprt

editor: source

